### ISSUE TITLE
/live/vmlinuz-6.1.0-9-amd64 not found

### ISSUE THREAD

**Issue by kip2choc** [RagnarokOS/distrib#2]
Hello Ian,
I tried the X11 iso but had this error after GRUB: 
error: file '/live/vmlinuz-6.1.0-9-amd64' not found.
I tried editing and removing /live (to mimic my installed debian) but without success.
I don't know what is the proper path since I don't know how the device is mounted.
Hope this helps. Can't wait to test the thing.
Thank you.

**Comment by IanLeCorbeau** [comment]
Wow, you're right it doesn't boot at all in UEFI mode (if only github had notified me of this issue before I built the ISO I was about to push just now). This is rather odd since it worked the last time I tried it.

Thanks for reporting the issue, I'll fix it as soon as possible. In the mean time, if you can boot in bios/legacy mode, it works without a hitch.

**Comment by IanLeCorbeau** [comment]
Ok, I'm an idiot. It doesn't work because the kernel was updated, so vmlinuz-6.1.0-9 doesn't exist anymore. It works in bios mode because syslinux uses /live/vmlinuz and /live/initrd.img (without the version number).

This will be fixed in the next iso release, which should come up later today.

**Comment by kip2choc** [comment]
Fixed, thanks!
